repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: helm-git-test
    url: git+https://github.com/jaroslaw-osmanski/helm-git-test/@?ref=feature-test

releases:
 - name: deployment
   chart: helm-git-test/test-chart
   # calculated from environments
   timeout: 1200

helmDefaults:
  kubeContext: minikube

